### ISSUE TITLE
Missing objects365.patch5.tar.gz

### ISSUE THREAD

**Issue by xingyizhou** [ozendelait/rvc_devkit#13]
Hi @patienceFromZhou @ozendelait ,
  Thanks for the great benchmark. It seems that objects365.patch5.tar.gz is missed from the ASW link. Can you check that?

**Comment by ozendelait** [comment]
Confirmed; currently objects365.patch5.tar.gz is not part of s3://objects365/objects365-v2-released/
@patienceFromZhou : please add the missing file to the aws folder

**Comment by patienceFromZhou** [comment]
> Hi @patienceFromZhou @ozendelait ,
> Thanks for the great benchmark. It seems that objects365.patch5.tar.gz is missed from the ASW link. Can you check that?

Fixed, thanks for the issue.
