### ISSUE TITLE
About MVS annotation in COCO format

### ISSUE THREAD

**Issue by xingyizhou** [ozendelait/rvc_devkit#14]
Hi @pkontschieder ,
  By following the instruction, it seems that the coco-format json file used [here](https://github.com/ozendelait/rvc_devkit/blob/master/objdet/remap_obj_det.sh#L72) is missing for Mapillary Vista. Is this the same one created in [this repo](https://github.com/mapillary/seamseg/blob/master/scripts/data_preparation/prepare_vistas.py)? 

  Also, the [extracting data script](https://github.com/ozendelait/rvc_devkit/blob/master/objdet/extract_and_cleanup.sh#L58) assumes the MVS dataset version is v1.1, while the most recent version I requested if v1.2. Can I assume I can use v1.2 for the challenge since there is no much difference between the versions?

**Comment by ozendelait** [comment]
@xingyizhou : until we get a confirmation, I have added the prepare_vista script as a step during the extractor step. Please test this script:
https://github.com/ozendelait/rvc_devkit/blob/master/segmentation/convert_mvd_coco.sh
I have renamed all "mvs" abbreviations to the correct "mvd". All you have to do is rename the mvs folder, everthing else stay the same

**Comment by ozendelait** [comment]
Oh, and I also updated the extractor to use v1.2 instead of v1.1 although both should work with the converter script and both are fine for usage during training

**Comment by pkontschieder** [comment]
The difference between v1.1 and v1.2 is that RGB images now have privacy blurring. There is no difference wrt data loading, filenames, etc. @xingyizhou @ozendelait

**Comment by ozendelait** [comment]
Thanks for the clarification. Issue closed
