### ISSUE TITLE
Error when remapping semantic segmentation

### ISSUE THREAD

**Issue by tmensink** [ozendelait/rvc_devkit#19]
When running the remapping (`remap_sem_segm.sh`)
The following warning / error is issued:

```
usage: rvc_add_dataset_mseg.py [-h] --panoptic_json PANOPTIC_JSON --orig_dname
                               ORIG_DNAME [--img_subfolder IMG_SUBFOLDER]
                               [--annot_subfolder ANNOT_SUBFOLDER]
rvc_add_dataset_mseg.py: error: unrecognized arguments: {split}/pano/{file_name[0]}{file_name[1]}{file_name[2]}
```

**Comment by ozendelait** [comment]
Hi, please test the faulty line with quotes:

python rvc_add_dataset_mseg.py --panoptic_json "${RVC_DATA_SRC_DIR}/viper/{split}/pano.json" --orig_dname viper-rvc --img_subfolder "{split}/img/{file_name[0]}{file_name[1]}{file_name[2]}"  --annot_subfolder panoptic "{split}/pano/{file_name[0]}{file_name[1]}{file_name[2]}"

Is this working for you? Which shell are you using?

**Comment by ozendelait** [comment]
I have fixed the faulty line in the scripts; it currently works on my test system (uses /bin/bash)
