### ISSUE TITLE
VIPER Camera Pose info 

### ISSUE THREAD

**Issue by soyebn** [ozendelait/rvc_devkit#26]
Where can I find text file containing camera pose info of "playing for benchmark" dataset?

The following link is supposed to have it but I can't find it under which zip it is present.
https://playing-for-benchmarks.org/download/
says, "We provide the camera poses as one TXT file for each video sequence."

**Comment by srrichter** [comment]
The files were temporally down and are back online now.

**Comment by soyebn** [comment]
Appreciate for taking care of it quick.

Regards, Soyeb
---------------------------------------------------------------------
