### ISSUE TITLE
Submission to COCO Detection (Bounding Box) failed

### ISSUE THREAD

**Issue by xingyizhou** [ozendelait/rvc_devkit#29]
Hi @ozendelait @tylin 
  I am trying to submit to the RVC COCO detection test-challenge server. However, it returns "Failed" and the error message is below:

~~~
Traceback (most recent call last):
  File "/worker/worker.py", line 330, in run
    if input_rel_path not in bundles:
TypeError: argument of type 'NoneType' is not iterable
~~~

I have submitted to the RVC COCO test-dev server and it evaluated successfully. I also checked my submitted file and can ensure it is not broken. Could it be a problem of the evaluation server? When can I try a second submission?

Best,
Xingyi

**Comment by xingyizhou** [comment]
Closing as it is evaluated now.

**Comment by garyfanhku** [comment]
Hi @xingyizhou, 

we ran into the same issue when submitting to the test-challenge server. I wonder if you would be kind enough to share how you make the evaluation work. Much appreciated!

Also, as is indicated in #30 , each team is entitled to 5 submissions. May I know if the failed submissions also count towards the 5? Many thanks for your time. @tylin

**Comment by tylin** [comment]
This is a known CodaLab issue. Please re-run the submission after a few hours. The failed submission won't count towards the max submission.

**Comment by xingyizhou** [comment]
Yes, I just waited for a few hours and the submission was automatically evaluated. I didn't resubmit. BTW, I just submitted to the COCO instance segmentation server and the same thing happened ...

**Comment by xingyizhou** [comment]
Hi @tylin . my instance submission with the same error did not get re-evaluated for 7 hours. Is it suggested to submit the same result again? Will the previous submission be automatically re-evaluated when the server is operational?

**Comment by garyfanhku** [comment]
Hi @xingyizhou, thanks for the reply. In my case, the results got automatically re-evaluated after 4 hours.

**Comment by tylin** [comment]
Hi @xingyizhou I manually re-ran your submission and it seems to work now. Let me know if you have any question.

**Comment by xingyizhou** [comment]
Thanks Tsung-Yi, it worked!

**Comment by hjxhhh** [comment]
Hi @tylin , my submission to object detection on COCO is failed. Please give me a hint how could I do for this? I really wish to make a submission before deadline. Thanks!
