### ISSUE TITLE
COCO detection leaderboard is set to private

### ISSUE THREAD

**Issue by xingyizhou** [ozendelait/rvc_devkit#30]
Hi @tylin 
  The COCO detection leaderboard (test-challenge) is set to private, and I can not see my test-challenge evaluation results in the submission panel. Is this on purpose? Will the detection leaderboard be complete only after the challenge deadline if so?

**Comment by tylin** [comment]
Hi @xingyizhou 
I open the leaderboard now so you can see your results. Note that one team only has most submit 5 entries in total.

**Comment by xingyizhou** [comment]
Thanks!
