### ISSUE TITLE
VIPER flow submission not implemented

### ISSUE THREAD

**Issue by tobyweed** [ozendelait/rvc_devkit#31]
The `CreateSubmission` and `CanCreateSubmissionFromFormat` functions are not implemented in `benchmark_viper.py`, so creating submission archives for VIPER is not possible using the devkit.

**Comment by srrichter** [comment]
I'll add it to the devkit. In the meantime, have a look at the viper toolkit, specifically [https://github.com/srrichter/viper/blob/master/prepare_submission.py](url)
