### ISSUE TITLE
VIPER panoptic format unspecified

### ISSUE THREAD

**Issue by ozendelait** [ozendelait/rvc_devkit#32]
Submission format description for VIPER is missing. A "regular" COCO panoptic result file with image_ids == file_name without extension leads to a "submission with PQ==RQ==SQ==0

**Comment by srrichter** [comment]
This was a server-side problem. The regular panoptic format with a panoptic.json should work now. Please (also) use the file_name attribute when referring to individual images in the json file as this is used for evaluation. A submission zip can be prepared via [https://github.com/srrichter/viper/blob/master/prepare_submission.py](url)
