### ISSUE TITLE
How to write depth into .pfm file (VIPER)?

### ISSUE THREAD

**Issue by KexianHust** [ozendelait/rvc_devkit#35]
Hi, is there any example for saving the predicted depth?
Thank you!

**Comment by srrichter** [comment]
Depth maps are expected to be of size 1080x1920 and in .pfm format. An example function for saving pfm-files can be found e.g. here: [MiDaS/utils.py:write_pfm](https://github.com/intel-isl/MiDaS/blob/79eda44b0c353f314070115d60215ae214227053/utils.py#L59)

Using that function, you could convert your predicted depth maps stored as png files like that:
```
import pathlib
from imageio import imread
import numpy as np
from utils import write_pfm

for f in pathlib.Path('./predictions/').glob('**/*.png'):
    d = imread(f).astype(np.float32)
    write_pfm(f.with_suffix('.pfm'), d)
```

**Comment by KexianHust** [comment]
Thanks! One more question: are these uint16 or uint8  pngs files?  Do I need to multiple 256.0 when saving depth maps?

Best,


Ke Xian
School of Artificial Intelligence and Automation
Huazhong University of Science and Technology
Wuhan 430074, PR.China
Tel: +86 15071315784
Email: kexian@hust.edu.cn 
 
From: srrichter
Date: 2020-08-14 22:18
To: ozendelait/rvc_devkit
CC: Ke Xian; State change
Subject: Re: [ozendelait/rvc_devkit] How to write depth into .pfm file (VIPER)? (#35)
Depth maps are expected to be of size 1080x1920 and in .pfm format. An example function for saving pfm-files can be found e.g. here: MiDaS/utils.py:write_pfm
Using that function, you could convert your predicted depth maps stored as png files like that:
import pathlib
from imageio import imread
import numpy as np
from utils import write_pfm
for f in pathlib.Path('./predictions/').glob('**/*.png'):
    d = imread(f).astype(np.float32)
    write_pfm(f.with_suffix('.pfm'), d)

**Comment by KexianHust** [comment]
Thanks for your reply! One more question: are these uint16 or uint8 png files? Do I need to multiple 256.0 when saving the depth maps?

Thank you!

**Comment by srrichter** [comment]
Apart from the precision (16bit vs 8bit), this should not make a difference as depth predictions are (robustly, i.e. using median) scaled to match the ground truth scale before evaluating.
