### ISSUE TITLE
Submission to coco detection failed

### ISSUE THREAD

**Issue by hjxhhh** [ozendelait/rvc_devkit#36]
Hi @tylin , I think this is somewhat related to https://github.com/ozendelait/rvc_devkit/issues/29#issue-674529331. 
Our submission to object detection on COCO failed the same way. We have been attempting to submit a few times as suggested, and also waited a couple of hours hoping the benchmark will re-run like the last time, but so far none has succeeded. As the competition deadline is getting close. We hope maybe you can manually run the following two submissions as you have indicated in issue 29. Or if there are other ways to submit, please do let us know. 

Thanks!

 _Originally posted by @hjxhhh in https://github.com/ozendelait/rvc_devkit/issues/29#issuecomment-674055136_
![image](https://user-images.githubusercontent.com/23472001/90255094-5f9f3d00-de76-11ea-8857-fdb0ee971683.png)

**Comment by xingyizhou** [comment]
Same here for COCO. Also my Mapillary submission stays in "submitted" by not evaluating. Does it need a manual run as well? @ozendelait @pkontschieder

**Comment by ozendelait** [comment]
some MVD submissions may take up to a day to evaluate. We will count all submissions uploaded before the deadline as valid, regardless when they are evaluated/visible on the leaderboard.

**Comment by tylin** [comment]
@hjxhhh This is known CodaLab issue. I will re-run you submission you uploaded.
