### ISSUE TITLE
Wrong category number for object detection OID

### ISSUE THREAD

**Issue by sefira** [ozendelait/rvc_devkit#37]
hello,
I notice that there are only 443 categories for OID(oid_boxable_leaf) in https://github.com/ozendelait/rvc_devkit/blob/master/objdet/obj_det_mapping.csv. However, there should be 500 categories in OID challenge version.

Why some categories are absent?

Thank you very much.

**Comment by ozendelait** [comment]
The best-effort mapping only takes OID leaf-nodes into account
