### ISSUE TITLE
Get dataset: No response from rabbitAI

### ISSUE THREAD

**Issue by XiangMochu** [ozendelait/rvc_devkit#40]
I have tried to register at: https://rabbitai.de/benchmark/register/ to get the dataset link for the past few weeks, with several email addresses, but got no response. Is it just me or there is something off with the mail sending of rabbitAI?

**Comment by hendrikschilling** [comment]
Thanks for reporting,

I'll check back tomorrow, there is supposed to be an automated system in 
place.

Best
Hendrik

**Comment by jingk-song** [comment]
I have got the same problem, no response form rabbitAI, and I wonder how to deal with it.

**Comment by hendrikschilling** [comment]
Hi,

Sorry forgot to reply to list last time.

for now please use this direct download link:
https://download.rabbitai.de/benchmarks/rvc_2020/data.zip

Best

Hendrik

**Comment by ozendelait** [comment]
The download link will be used for all RVC2022 contestents. I also added the information to the depth toolkit description.
