### ISSUE TITLE
Something wrong when registering to the RVC challenge.

### ISSUE THREAD

**Issue by jingk-song** [ozendelait/rvc_devkit#41]
I have filled out the form to register to the RVC challenge at http://www.robustvision.net/submit.php#register. However, after submission I got this:
BACKUP ERROR: 2
copy(/home/rob/.bkp_methods/.20220727_084407_register_method.txt): failed to open stream: No such file or directory
at http://www.robustvision.net/register_method.php.

**Comment by ozendelait** [comment]
Hi, sorry about that. This was due to a server update. The registration form should work since 2 weeks ago.
