### ISSUE TITLE
mvd submission error

### ISSUE THREAD

**Issue by wuwuwuxxx** [ozendelait/rvc_devkit#46]
I have tried several times to submit segmentation results to codalab mvd benchmark and I got the same error. pls let me know how can I
submit successfully.
![1662262457605](https://user-images.githubusercontent.com/13163233/188296030-573e5540-22b2-4036-a525-40bdf49ff84e.png)

**Comment by ozendelait** [comment]
This looks like a server error; 
@pkontschieder : Please check the submission server

**Comment by acolovic** [comment]
@wuwuwuxxx I updated the docker path, can you try again and report back if submitting works for you?

**Comment by pawneshg** [comment]
Hello, @acolovic 

Receiving an error message, while running evaluation on validation set.
```
Unable to find image 'dtr.thefacebook.com/acolovic/rbv2022:v1' locally
docker: Error response from daemon: Get https://dtr.thefacebook.com/v2/: dial tcp: lookup dtr.thefacebook.com on 8.8.8.8:53: no such host.
See 'docker run --help'.
```

**Comment by pawneshg** [comment]
@acolovic It works now. But I am getting exception for "files not found"

`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpvS2b3r/run/input/res/Fvs0ddQyL5xyekEajtcokg.png'`

I did verification. The files are available in zip folder. 

I am not sure whether my zip file is uploaded completely or not. Is there any way to verify this?

**Comment by acolovic** [comment]
@pawneshg when it unzips your submission, there is a subfolder 'vistas' which contains all images. if you pack it without the subfolder, it should work. I just verified this.

**Comment by wuwuwuxxx** [comment]
> @wuwuwuxxx I updated the docker path, can you try again and report back if submitting works for you?
i try again and submitting works but i cant find the submit results.
![image](https://user-images.githubusercontent.com/13163233/190091896-3cc33e62-f5ad-4cad-b9f7-0edabeb17db6.png)
and I try to download output from scoring step , I get error like this
![image](https://user-images.githubusercontent.com/13163233/190092580-00d8f555-453e-4407-8e0f-93b741eda8b7.png)
and result page shows like this
![image](https://user-images.githubusercontent.com/13163233/190092761-d259e894-c392-43f2-87ba-32ee046ee37e.png)
pls let me know how can i get the submit results

**Comment by acolovic** [comment]
@wuwuwuxxx Validation leaderboards were private. I updated it, such that you should see your scores now. Test leaderboards are still hidden. I'll check if we want to change that or not.

**Comment by ozendelait** [comment]
@acolovic Thanks! Please make the test leaderboards visible too (both MVD Segm. & ObjDet. task)

**Comment by ozendelait** [comment]
Visibility is now fixed. Thanks Aleksander!
