### ISSUE TITLE
A Classes Number Question

### ISSUE THREAD

**Issue by LLccelerator** [ozendelait/rvc_devkit#47]
We are preparing for Robust Vision Challenge 2022(Obj. Det.), but we find a question recently.As you asked, our label space shoud not exceed 550 classes, while the OID dataset has 600 classes. So We do not think this limit is very reasonable.Is there any solutions or can you give us some other advice? Thanks!

**Comment by ozendelait** [comment]
OID boxable should have 500 classes as a maximum (see https://www.kaggle.com/competitions/open-images-object-detection-rvc-2022-edition and https://github.com/ozendelait/rvc_devkit/blob/master/common/label_definitions/oid-challenge-2019-classes-description-500.csv ); I have seen the number 600 pop up on the OID website. 
@akuznetso : please comment

**Comment by akuznetso** [comment]
We do think the subset of 500 classes we selected for the challenge is reasonable. We removed some very broad classes (e.g. "clothing") and some infrequent ones (e.g. "paper cutter"). This is to enable more precise mAP measurements.

**Comment by ozendelait** [comment]
Thanks Alina for the clarification.
@LLccelerator: 550 classes should be enough given the overlaps of classes between OID, COCO, MVD
