### ISSUE TITLE
RabbitAI evaluation unavailable

### ISSUE THREAD

**Issue by XiangMochu** [ozendelait/rvc_devkit#48]
The [link](https://rabbitai.de/download/rabbitai_submission_images.zip) to the rabbitAI benchmark submission images is currently not available, showing a 404 error when trying to download. We tried to contact rabbitAI through [benchmark@rabbitai.de](mailto:benchmark@rabbitai.de) but got no response.

**Comment by hendrikschilling** [comment]
After investigating the issue I am sorry to report that we will not be 
able to fix the issue in a reasonable timeframe. I am very sorry, both 
for the time you put into trying to submit
and for lost benchmark for the RVC community.

We have informed the organizers and will also put a disclaimer on the 
benchmark website.

Best Regards
Hendrik
