### ISSUE TITLE
Submission Error(Obj. Det.)

### ISSUE THREAD

**Issue by LLccelerator** [ozendelait/rvc_devkit#49]
Dear organizer,
	We are trying to upload the submission files(MVD), but we meet a question as shown in the enclosure.Is there any solutions or can you give us some other advice? Thanks!
<img width="418" alt="微信图片_20220911131344" src="https://user-images.githubusercontent.com/112802878/190299279-afc6bca3-bddb-4a4d-8311-276cf91bd411.png">

**Comment by ozendelait** [comment]
@acolovic please check the mvd obj det. Challenge docker paths as well

**Comment by LLccelerator** [comment]
We have checked the mvd obj det. Challenge docker paths, but the error still exists. Could you please check the submission system as soon as possible？Because there's not much time left. Thanks.
<img width="602" alt="微信图片_20220918233604" src="https://user-images.githubusercontent.com/112802878/190915340-6de9a4a2-c060-4da3-95a3-a282bc427ed8.png">

**Comment by ozendelait** [comment]
I will change the dev kit/website accordingly. Thanks Aleksander!
