### ISSUE TITLE
Viper not evulated (segmentation)

### ISSUE THREAD

**Issue by gepu0221** [ozendelait/rvc_devkit#51]
Dear organizer,
We are trying to evaluate our model result on viper dataset.  But after the result is uploaded, the status has been always 'not evaluated'. There seems to be some issues with the evaluation server. Is there any solutions or can you give us some other advice? Thanks!

**Comment by ozendelait** [comment]
@vkoltun : please check the status of the VIPER Segmentation benchmark

**Comment by srrichter** [comment]
Done. 

In case any evaluations on VIPER come back with a "Something went wrong" message, please ping us via the contact formular on the VIPER webpage, providing user name, method name, and submission ID.

**Comment by ozendelait** [comment]
Great, thanks Stephan!
