### ISSUE TITLE
Using sequential initialization

### ISSUE THREAD

**Issue by az-ja** [ozendelait/rvc_devkit#52]
Hi,

For optical flow methods, it is common to use the warped computed flow from previous frames in the sequence to have an improved initialization in the estimation process for the next frame. For some datasets the test sequence is not available and only single image-pairs are available.

Is that OK to use the sequence info if the dataset provides the test sequence, and not if the test sequence is not available (only single image pairs are available)?
Please note that this approach is input-type-dependent not dataset-dependent. When the previous frame is not available, naturally the flow cannot be initialized using previous test frames.

Thank you for your time.

**Comment by az-ja** [comment]
There are two datasets for each type. Sintel and Middle-bury use sequences. Viper and Kitti provide only single image pairs.

**Comment by az-ja** [comment]
Thank you for your answer!
I think I should clarify something: The input of the method is always 3 things in all cases and for all datasets: 2 consecutive images and an initial flow.
In the case of Sintel and Middle bury the initial flow can be estimated by forward warping the flow estimate of the previous image pair in the sequence. In other cases - if only single image-pairs are available or for the first image-pair in the sequence, since there is no previous image-pair - the zero flow is considered.
Passing zero flow is performing as if there is not prior motion, as the current image-pair is the only pair available. This is equivalent to passing the same image (as you suggested) since there is no movement between identical images. Would that be OK to consider zero initial flow for such cases?

About also submitting the single processed image pairs to Sintel and Middle bury, do you mean: we should report the accuracy gap in the technical report that needs to be submitted after the challenge's deadline.

**Comment by ozendelait** [comment]
Yes, this is fine. 
@single processed image: correct, this is valuable information for your presentation/report should you win

**Comment by az-ja** [comment]
Thank you very much for your time and answer!
