### ISSUE TITLE
training with test data?

### ISSUE THREAD

**Issue by wuwuwuxxx** [ozendelait/rvc_devkit#53]
hi, for obj. segmentation during training can we use test data for some unsupervised learning method?

**Comment by ozendelait** [comment]
Benchmarking data (e.g. images part of the benchmark testset) are not to be used until inference for leaderboard submissions; not for parameter tweeking and not for any training.
If an unrelated public dataset offers a second validation set with public GT which they call "test data", then this may be used during training as well.
