### ISSUE TITLE
the class num of wilddash

### ISSUE THREAD

**Issue by wuwuwuxxx** [ozendelait/rvc_devkit#54]
hi,  in wd_public_v2p0.zip,  there are 80 classes in wilddash2-meta.json,  the period "evalute" of some class are false.  in wilddash2-eval-meta.json, there are only 38 classes.  But some classes with period "evulate" True not appear in wilddash2-eval-meta.json. And there is no class map file about how to map the train class to test class. So pls tell me the class num of wilddash test datasets and if it is same with wilddash2-eval-meta.json, pls tell me how can i get the class map file to map  wilddash2-meta.json classes to wilddash2-eval-meta.json classes.

**Comment by ozendelait** [comment]
Hi, Wilddash2 final version benchmark uses the evaluation classes of the beta phase (renamed to WD2_eval in the paper). The relevant class number is thus the one found in wilddash2-eval-meta.json. 
The mapping found in the rvc_devkit is thus still valid. I did not update the dev kit to prevent this kind of confusions but of course the final version is more suited to the task as WD2 now includes all MVD and IDD labels as well (the beta only had the 39 class subset). You can use both the old beta data wd_public_02.zip and/or the final version from wd_public_v2p0.zip for training. 
The benchmarking part of Wilddash 2 has not changed (same wd_both_02.zip as previously).

**Comment by wuwuwuxxx** [comment]
> Hi, Wilddash2 final version benchmark uses the evaluation classes of the beta phase (renamed to WD2_eval in the paper). The relevant class number is thus the one found in wilddash2-eval-meta.json. The mapping found in the rvc_devkit is thus still valid. I did not update the dev kit to prevent this kind of confusions but of course the final version is more suited to the task as WD2 now includes all MVD and IDD labels as well (the beta only had the 38 class subset). You can use both the old beta data wd_public_02.zip and/or the final version from wd_public_v2p0.zip for training. The benchmarking part of Wilddash 2 has not changed (same wd_both_02.zip as previously).

But I want to know the class in ground truth of the benchmarking part of wilddash2. For example, a banner on the building is labelled as class "building" in the beta phase, but is labelled as class "banner"  in the final version, so which class will it be  in the benchmarking part?
