### ISSUE TITLE
A New Submission Error in MVD (Obj.Det.)

### ISSUE THREAD

**Issue by LLccelerator** [ozendelait/rvc_devkit#55]
After replacing the submission system, we tried to submit again and encountered new problems, (as shown in the figure). Can you give us some help and suggestions? Thanks!
<img width="404" alt="微信图片_20220921173322" src="https://user-images.githubusercontent.com/112802878/191473848-b25380a7-2ef9-4a76-aadd-f1d081ed1649.png">

**Comment by ozendelait** [comment]
@acolovic Please check the submission server; is this a GT problem?

**Comment by ozendelait** [comment]
@LLccelerator : Two suggestions (from https://github.com/ozendelait/rvc_devkit/blob/master/objdet/README.md ):   1) make sure all 'image_id' keys have 22 character string values; 2) Filename before zipping should be detections_test_METHOD_results.json 
Your method is not named 001 right?

**Comment by acolovic** [comment]
@LLccelerator I tried to mention this also here https://github.com/ozendelait/rvc_devkit/issues/49#issuecomment-1252022571

Our GT test set has image_ids that are 22char strings. (In the dataset, the names of the images in the folder testing/images/<image_id>.jpg)

if you put numbers in your submission, we don't know which image you are referring to and trigger the assertion you see above.

Please use the correct image_ids and submit again. I tested one of your previous submissions by just replacing the image_id with random, valid ids and the evaluation code finished.
