### ISSUE TITLE
<method-name_RVC> submission made across stereo benchmarks but not displayed on leaderboard.

### ISSUE THREAD

**Issue by AntiLibrary5** [ozendelait/rvc_devkit#57]
Hi, 
Following the instructions:

![image](https://user-images.githubusercontent.com/48105310/191782233-4c56a198-0fed-467c-a7d7-f01e8cf489bd.png)

Our model does not appear on the leaderboard.

Thank you,
Best.

**Comment by ozendelait** [comment]
Hi, the crawler operates manually. We start it about 2-3 times per week. Please check the date/time displayed as "last updated" under the leaderboard  for more information. I think your submission now shows on the leaderboard?

**Comment by AntiLibrary5** [comment]
Sorry I missed that piece of information below and did assume it was automatic. Its all good now. Thank you.
