### ISSUE TITLE
Question about KITTI dataset

### ISSUE THREAD

**Issue by TomTomTommi** [ozendelait/rvc_devkit#58]
Which KITTI dataset is used in rankings for Stereo Matching track? KITTI2012 or KITTI2015 or both of these two?

**Comment by az-ja** [comment]
Hi,
Could you please also answer this question for optical flow? I saw that in previous years, the methods submitted to Kitti 2015 only. But it would be nice to make sure.

**Comment by ozendelait** [comment]
Yes, both Stereo and Flow use only KITTI2015 leaderboards
