### ISSUE TITLE
Boxable Version of MVS

### ISSUE THREAD

**Issue by ozendelait** [ozendelait/rvc_devkit#6]
Is there a timeline for boxable version of MVS? Which data format will you use for your release?

**Comment by pkontschieder** [comment]
The devkit should still work as is. As you may know, it has become common practice to only provide anonymized images and we used this opportunity to do so with Vistas now. Also, it took some time to confirm that this won't impact the results on affected classes.

**Comment by ozendelait** [comment]
Thanks for the clarification! Issue closed.
