### ISSUE TITLE
 wilddash2 benchmark class 

### ISSUE THREAD

**Issue by wuwuwuxxx** [ozendelait/rvc_devkit#60]
> Hi, Wilddash2 final version benchmark uses the evaluation classes of the beta phase (renamed to WD2_eval in the paper). The relevant class number is thus the one found in wilddash2-eval-meta.json. The mapping found in the rvc_devkit is thus still valid. I did not update the dev kit to prevent this kind of confusions but of course the final version is more suited to the task as WD2 now includes all MVD and IDD labels as well (the beta only had the 38 class subset). You can use both the old beta data wd_public_02.zip and/or the final version from wd_public_v2p0.zip for training. The benchmarking part of Wilddash 2 has not changed (same wd_both_02.zip as previously).

But I want to know the class in ground truth of the benchmarking part of wilddash2. For example, a banner on the building is labelled as class "building" in the beta phase, but is labelled as class "banner"  in the final version, so which class will it be  in the benchmarking part?

_Originally posted by @wuwuwuxxx in https://github.com/ozendelait/rvc_devkit/issues/54#issuecomment-1254398039_

**Comment by ozendelait** [comment]
The GT for benchmarking frames for Wilddash2 has not changed and is the same as during the beta phase. In your example "building"
