### ISSUE TITLE
MVD (Semantic) not shown at the leaderboard

### ISSUE THREAD

**Issue by gepu0221** [ozendelait/rvc_devkit#61]
Dear organizer,
We submit our model results on the MVD dataset used the method name with postfix _RVC.  The evaluation has been completed and we got the scores, but no results are shown at the leaderboard after the last update. I wan to know if there is something wrong with the submission process. Can you give us some other advice? Thanks!

**Comment by zhangxgu** [comment]
Maybe you can use "submit to the leadboard" button on the submission page.

**Comment by gepu0221** [comment]
> Maybe you can use "submit to the leadboard" button on the submission page.

Yes, I do use this.

**Comment by ozendelait** [comment]
Looks like a bug in our ranking collection. I'm looking into it. Expect the rankings to appear in the next two days.

**Comment by ozendelait** [comment]
Ranking for MVD Sem. Segm. has been added to the leaderboard. This requires a manual mapping for codalab username<->Method; if your method is missing in the leaderboard; please post this missing information here. We will of course add this also after the submission deadline; so if you have a visible score on the MVD colab leaderboard, then this will in the final ranking for the challenge
