### ISSUE TITLE
A Submission Error in ADE(Semantic)

### ISSUE THREAD

**Issue by Abner0001** [ozendelait/rvc_devkit#62]
I tried two commits on ade's commit server. The first time I successfully uploaded and got the evaluation result, the second I got an error, but I observed the structure of the two zips locally without any difference.
![1](https://user-images.githubusercontent.com/34506191/192679084-f4d4a5ba-fdd0-4e0b-9006-87a93ca345f1.jpg)

**Comment by Abner0001** [comment]
Now I get a new error
![2](https://user-images.githubusercontent.com/34506191/192681731-4cccbd22-897e-4827-af12-6344da0df47e.png)

**Comment by ozendelait** [comment]
@xavierpuigf Please check the ADE20k submission server

**Comment by Abner0001** [comment]
> @xavierpuigf Please check the ADE20k submission server


Now the problem has been solved, thanks.

But I'm having some trouble with viper and cityscapes right now. The cityscapes I have completed the evaluation, then I applied to publish my evaluation results, but now more than ten hours have passed,  the administrator still seems to have not passed my request, it's always in pending. 
![2](https://user-images.githubusercontent.com/34506191/193187279-02a7cc54-9976-4e3a-ad89-558eb5395efe.png)

And there seems to be some problem with viper official server, every time I submit it returns an error 'Something went wrong with the evaluation', I once contacted their admin, the admin asked me to provide username and submission ID, but I didn't receive any follow-up messages after I provided them with the needed information, can you give me some help?
![1](https://user-images.githubusercontent.com/34506191/193187313-f9f3d618-8621-4ca7-ad58-1dc854d54e36.jpg)

**Comment by ozendelait** [comment]
Don't worry; we are accepting all submission which were handed in before the submission deadline regardless of when the final result from the evaluation is ready. 
Cityscapes has manual processes for evaluations so it might take some time. If you have contacted the admin of VIPER already, then this will also be solved soon. Please continue submitting to the remaining leaderboards.
