### ISSUE TITLE
COCO (obj det) Submission Error: Execution time limit exceeded!

### ISSUE THREAD

**Issue by linfeng93** [ozendelait/rvc_devkit#64]
the scoring error log as follows:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Execution time limit exceeded!

but my submission of the mvd dataset was finished successfully.

the det result format:
[{
"image_id": str,
"category_id": int,
"bbox": [x,y,width,height],
"score": float,
}]

any advices? thanks

**Comment by ozendelait** [comment]
Hi, COCO evaluation server is still being rebuild. Please see this issue for updates:
https://github.com/ozendelait/rvc_devkit/issues/56
Please proceed to submit to OID in the meantime.

**Comment by linfeng93** [comment]
> Hi, COCO evaluation server is still being rebuild. Please see this issue for updates: #56 Please proceed to submit to OID in the meantime.

ok
btw, will the ddl be postponed? @ozendelait
