### ISSUE TITLE
CodaLabs/ObjDet Team Name <-> Method

### ISSUE THREAD

**Issue by ozendelait** [ozendelait/rvc_devkit#66]
The RVC joint leaderboard only accesses public leaderboard websites. The OID, MVD and COCO leaderboards only show team names/usernames next to the ranked leaderboard. Thus we are missing the connection between your user and your method's name (which you must register here: http://www.robustvision.net/submit.php#register ).
To allow a real-time feedback, please post your teamname/username from OID and/or codalabs here. I will then add this information to our crawler and your submissions can be ranked correctly. We will check this information from the registration information (or collect missing connections manually) once the submission deadline has been passed.

**Comment by gguang10** [comment]
I used different email addresses when I registered CodaLab and Kaggle. Is this OK?
And how to calculate the proportion of the scores of the three data sets in the final scores?

**Comment by zhangxgu** [comment]
Team Name: mashangbai 
Method: mmdet_based_RVC/ mashangbai_RVC
username: zhangxgu

**Comment by linfeng93** [comment]
Team Name: IFFF
Method: Intellifusion_RVC
username: linfeng

**Comment by ozendelait** [comment]
@gguang10 Yes, you can use diffent email adresses. Please enter the same team name where possible and post the connection username/team name <-> method here

**Comment by linfeng93** [comment]
@ozendelait 
Hi, could you please change our “method” info on the RVC leaderboard? 
thanks

Team Name: IFFF
**Method: Intellifusion_RVC -> IFFF_RVC**
username: linfeng

**Comment by zhangxgu** [comment]
@ozendelait
Hi, I also want to  change our team name and method on the RVC leaderboard.
thanks

Team Name: mashangbai_RVC -> AntDet
Method: mashangbai_RVC -> CBS_Cascaded_resnext_RVC
username: zhangxgu

**Comment by ozendelait** [comment]
Renaming done; CBS_Cascaded_resnext_RVC was too long; I had to change it to CBS_CascResnxt_RVC

**Comment by kbyran** [comment]
@ozendelait Please check my team information below. thx!
Team name: TY
Method name: MD_RVC (Although I used the name MD in my submission, I feel that the MD_RVC is the most appropriate)
User name: kbyran

**Comment by gguang10** [comment]
Team Name: trytry
Method: USTC_RVC
username: USTC-IAT-united

**Comment by gguang10** [comment]
Team Name: trytrytry
Method: USTC_RVC
username: USTC-IAT-united
