### ISSUE TITLE
Questions about the third place

### ISSUE THREAD

**Issue by gguang10** [ozendelait/rvc_devkit#72]
Hi, do we need to submit a report for the third place, and is there a prize or award for the third place?

**Comment by ozendelait** [comment]
Thank you for participating! Sorry, only the winner and the runner-up receive prizes. We are currently evaluating the validity of the other submissions, so if we have to reject contest winners, third places will be declared runner-up instead. This is not very likely but it is still a possibility.
In any case: the full RVC leaderboard will be preserved and can be found on robustvision.net 
This show your Team’s name  (if you deselected “Keep Anonymous”) and reference to your project page. Feel free to add this ranking to your CV or mention it in a publication.

Also if you have something fitting to the RVC theme, then please submit to Track 1 of our IJCV special issue: https://www.springer.com/journal/11263/updates/20293358 
I hope to see you at our workshop on October 23rd!
